on: [push]

jobs:
  rector:
    runs-on: ubuntu-latest
    name: Rector
    steps:

      # Prepare repo -> it will be mounted into container via volume
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@2.8.0
        with:
          php-version: 7.4
          coverage: none
          tools: composer:v2

      # Testing action itself
      - uses: ./
